// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgOHbdcFizIO7sGIiKN42r80p6d7X0VFg',
    appId: '1:370753423546:web:8da43278960bdabf545a83',
    messagingSenderId: '370753423546',
    projectId: 'lucrao-app',
    authDomain: 'lucrao-app.firebaseapp.com',
    storageBucket: 'lucrao-app.firebasestorage.app',
    measurementId: 'G-FE0HW0FBE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2DesS0RsGKeEs6kErQN3eaBldhyBdl_8',
    appId: '1:370753423546:android:b1d95f8422c2fa7f545a83',
    messagingSenderId: '370753423546',
    projectId: 'lucrao-app',
    storageBucket: 'lucrao-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD02au48HO44O57ecKI5yaALCyUc2wo82U',
    appId: '1:370753423546:ios:9bb96913ffe05515545a83',
    messagingSenderId: '370753423546',
    projectId: 'lucrao-app',
    storageBucket: 'lucrao-app.firebasestorage.app',
    iosBundleId: 'com.example.lucrao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD02au48HO44O57ecKI5yaALCyUc2wo82U',
    appId: '1:370753423546:ios:9bb96913ffe05515545a83',
    messagingSenderId: '370753423546',
    projectId: 'lucrao-app',
    storageBucket: 'lucrao-app.firebasestorage.app',
    iosBundleId: 'com.example.lucrao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgOHbdcFizIO7sGIiKN42r80p6d7X0VFg',
    appId: '1:370753423546:web:8fef9c10d7fa776a545a83',
    messagingSenderId: '370753423546',
    projectId: 'lucrao-app',
    authDomain: 'lucrao-app.firebaseapp.com',
    storageBucket: 'lucrao-app.firebasestorage.app',
    measurementId: 'G-3199M5GFEN',
  );

}